const ORDER_NAME = 'name';
const ORDER_MOBILE = 'mobile';
const ORDER_ADDRESS = 'address';
const ORDER_STATE = 'state';
const ORDER_PIN = 'pin';
const ORDER_PRODUCTS = 'products';
const PRODUCT_QUANTITY = 'quantity';
const ORDER_CREATED_BY_ID = 'created_by_id';
const ORDER_CREATED_BY_EMAIL = 'created_by_email';
const ORDER_ORIGIN = 'origin';
const ORDER_CREATED_AT = 'created_at';
const ORDER_MODIFIED_LAST = 'modified_last';

const CUSTOM_ORDER_GENERATE_KEY = 'custom';
const PROGRAM_ORDER_GENERATE_KEY = 'program';

const ORDER_STATUS = 'status';
const ORDER_STATUS_CREATED = 'created';
const ORDER_STATUS_CANCELED = 'canceled';
const ORDER_STATUS_DISPATCHED = 'dispatched';
const orderStatuses = [ORDER_STATUS_CREATED, ORDER_STATUS_CANCELED, ORDER_STATUS_DISPATCHED];

module.exports = {
  ORDER_NAME,
  ORDER_MOBILE,
  ORDER_ADDRESS,
  ORDER_STATE,
  ORDER_PIN,
  ORDER_PRODUCTS,
  PRODUCT_QUANTITY,
  ORDER_CREATED_BY_ID,
  ORDER_CREATED_BY_EMAIL,
  ORDER_ORIGIN,
  ORDER_CREATED_AT,
  ORDER_MODIFIED_LAST,
  CUSTOM_ORDER_GENERATE_KEY,
  PROGRAM_ORDER_GENERATE_KEY,
  ORDER_STATUS,
  ORDER_STATUS_CREATED,
  ORDER_STATUS_CANCELED,
  ORDER_STATUS_DISPATCHED,
  orderStatuses
};